### ISSUE TITLE
Unreliable parsing of ZSH history

### ISSUE THREAD

**Issue by benteg** [nate-sys/muc#14]
I'm seeing multiple issues when using muc with a standard ZSH / oh-my-zsh history file:

- The top command is shown as `0`...
  ![image](https://user-images.githubusercontent.com/104420015/209685991-30b55416-e018-43f3-b203-98f9236777dd.png)

- ...and command timestamps are listed as individual commands:
  ![image](https://user-images.githubusercontent.com/104420015/209686743-46f6dbe8-a973-4725-add1-11be45fffabb.png)

  Relevant lines:

  ```
  : 1662623233:0;some command
  : 1662623254:0;another command
  ```
- URLs get included as commands but with the `https:` cut off:
  ![image](https://user-images.githubusercontent.com/104420015/209686880-40ca2fcf-70b4-4cbe-87d4-a14bd26d5944.png)

  Relevant lines:

  ```
  : 1670425618:0;curl -fsSL https://raw.githubusercontent.com/spicetify/spicetify-cli/master/install.sh | sh\
  curl -fsSL https://raw.githubusercontent.com/spicetify/spicetify-marketplace/main/resources/install.sh | sh
  ```

---

Installed version: d4bb4c65 (0.1.0)

**Comment by nthnd** [comment]
I'm not sure how accurate I can make this. I've realized there are so many factors at play when it comes to parsing history files, and simply reading the first word of every line wont work. The program works by reading every line, splitting the line with the specified `--separators` and then taking the first word assuming that it is a command. It doesn't check if  a semicolon was meant to be ignored because it was in a string or if a colon was meant to be ignored because it was in a url. 

For now, I can only advise you to play around with the `--separators` until the output looks somewhat accurate. Or submit a pr if you have a better way of handling the data.

**Comment by benteg** [comment]
Seems to work fine with `--separators "&|;"`, thanks :)
