### ISSUE TITLE
[Feature Request] Common flags for common shells

### ISSUE THREAD

**Issue by dmadisetti** [nate-sys/muc#17]
It would be nice to have `--fish` as the recommend option over `--prefix="- cmd: "` or even `--shell=fish`. Same for ZSH etc.

The shell specific flags could jut be aliases to more complex flags

**Comment by nthnd** [comment]
I tried implementing this in my previous iteration. Initially, I thought it would be better to hard code the algorithm for all of the shells into the source code. I found I was being too ambitious so I scrapped it and decided to design it in a way that users can sort of dictate how they want their history parsed: `--prefix` and `--separators`. 

I think this is a better option, especially since  regex is almost available. This way, it's just a matter of adding a sample command to the readme file for common shells.

I'd like to hear more suggestions, however.

**Comment by nthnd** [comment]
Closing because #16 is merged
